version: '3'

services:
  app:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
    ports:
      - "5432:5432"
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"